services:
  swift-app:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
        - linux/arm64
    restart: unless-stopped
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - USR_TOKEN=${USR_TOKEN}
    ports:
      - '8080:8080'
